Refactoring for DI + Event Bus pattern
Need to resolve issue:

KeyNotFoundException: The given key '5050' was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <321eb2db7c6d43ea8fc39b54eaca3452>:0)
SpatialGroupManager.GetAllEnemiesInSpatialGroups (System.Collections.Generic.List`1[T] spatialGroups) (at Assets/Scripts/SpatialGroupManager.cs:200)
PlayerController.CalculateNearestEnemyDirection () (at Assets/Scripts/PlayerController.cs:140)
PlayerController+<PlayerMainLoop>d__24.MoveNext () (at Assets/Scripts/PlayerController.cs:95)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <b5bf0c891ea345fe93688f835df32fdc>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
PlayerController:Handle_StartGame() (at Assets/Scripts/PlayerController.cs:70)
GameEvents:StartGame() (at Assets/Scripts/GameEvents.cs:12)
GameController:Start() (at Assets/Scripts/GameController.cs:37)